### PR TITLE
feat: support the `toJson()` function

### PR DESCRIPTION
**Pull request by adil192**

### CODE REVIEW

**Comment by giorgiofran** [comment]
Hi, I'm sorry but I have not understood the logic of your changes. 
Could you please provide some tests? Maybe that with some example it becomes clearer to me. Thanks in advance.

**Comment by adil192** [comment]
Does this test help?

**Comment by giorgiofran** [comment]
Thanks, your test helped.
Cannot you take a diferent approach for serializing-deserializing like the following?

``` dart
import 'package:bson/bson.dart';

abstract class Serializable {
  const Serializable();
  Map<String, dynamic> toJson();

  BsonBinary serialize() {
    var bson = BSON();
    return bson.serialize(toJson());
  }
}

/// Example class that implements toJson and fromJson
class _Person extends Serializable {
  final String name;
  final int age;

  const _Person(this.name, this.age);

  _Person.fromJson(Map<String, dynamic> json)
      : name = json['name'],
        age = json['age'];

  static _Person deserialize(BsonBinary bsonBinary) {
    var bson = BSON();
    var objMap = bson.deserialize(bsonBinary);
    return _Person.fromJson(objMap);
  }

  @override
  Map<String, dynamic> toJson() => {'name': name, 'age': age};
}
```

**Comment by adil192** [comment]
If I understand you correctly, you're referring to having a base class (or better yet, a mixin) like `Serializable` so that instead of having
```dart
  BsonObjectFrom(var value) {
    // ...
    else {
      return BsonObjectFrom(value.toJson());
    }
}
you'd have:
```dart
  BsonObjectFrom(var value) {
    // ...
    else if (value is Serializable) {
      return value.serialize();
    }
}
```

This approach would work too, but I feel like it would be easier for the developer to not have to worry about BSON-specific methods when they're switching from JSON to BSON

**Comment by giorgiofran** [comment]
The idea is not to change the `Bson `methods, but if you have to serialize, you can simply call the `serialize `method of your class (ex. `var bsonBinary = john.serialize();`), and, if you have to deserialize, simply call the `deserialize` method (ex. `var john = Person.deserialize(bsonBinary);`)
In development you have only to extend the abstract class and create the `deserialize `method, that is similar for all the classes (the only change is the name of the class returned and of the class name for the call to `fromJson`).

**Comment by adil192** [comment]
I don't think that approach would work with nested objects, since you'd need every object returned from the `toJson()` method to be a simple type.
E.g.
```dart
/// extending on the tests, [marriage] contains two [_Person] objects
final bson = marriage.serialize();
// throws error that BSON.bsonObjectFrom is 'Not implemented for _Person'

**Comment by giorgiofran** [comment]
There are many serialization patterns, and several ways to do this kind of job.
What I would like to explain is that I'd prefer to maintain the BSON class dedicated to its original design.
I would like no to add internally some Object serialization stuff.

Just as an example I have prepared a fast test of how you could use the BSON classes for a serialization logic:

``` dart
import 'package:bson/bson.dart';
import 'package:fixnum/fixnum.dart';
import 'package:test/test.dart';

void main() {
  group('Run', () {
    test('with simple class', () {
      final john = Person('John', 30);

      // First test the toJson implementation of the example class
      final johnCloneFromJson = Person.deserialize(john.serialize());
      expect(johnCloneFromJson.name, john.name);
      expect(johnCloneFromJson.age, john.age);
    });

    test('with embedded objects', () {
      final john = Person('John', 30);
      final jane = Person('Jane', 31);
      final marriage = Marriage(DateTime(1990, 5, 22), john, jane);

      // First test the toJson implementation of the example class
      final marriageCloneFromJson = Marriage.deserialize(marriage.serialize());

      expect(marriageCloneFromJson.date, marriage.date);
      expect(marriageCloneFromJson.spouse1.name, marriage.spouse1.name);
      expect(marriageCloneFromJson.spouse1.age, marriage.spouse1.age);
      expect(marriageCloneFromJson.spouse2.name, marriage.spouse2.name);
      expect(marriageCloneFromJson.spouse2.age, marriage.spouse2.age);
    });
  });
}

dynamic _deserialize(BsonBinary bsonBinary, Function fromJson) {
  var bson = BSON();
  var objMap = bson.deserialize(bsonBinary);
  return fromJson(objMap);
}

abstract class Serializable {
  const Serializable();
  Map<String, dynamic> toJson();

  BsonBinary serialize() {
    var data = toJson();
    var newData = <String, dynamic>{};
    for (var entry in data.entries) {
      if (entry.value is Serializable) {
        newData[entry.key] = entry.value.serialize();
      } else {
        newData[entry.key] = entry.value;
      }
    }

    return BSON().serialize(newData);
  }
}

/// Example class that implements toJson and fromJson
class Person extends Serializable {
  final String name;
  final int age;

  const Person(this.name, this.age);

  Person.fromJson(Map<String, dynamic> json)
      : name = json['name'],
        age = json['age'];

  static Person deserialize(BsonBinary bsonBinary) =>
      _deserialize(bsonBinary, Person.fromJson);

  @override
  Map<String, dynamic> toJson() => {'name': name, 'age': age};
}

class Marriage extends Serializable {
  final DateTime date;
  final Person spouse1;
  final Person spouse2;

  const Marriage(this.date, this.spouse1, this.spouse2);

  Marriage.fromJson(Map<String, dynamic> json)
      : date = DateTime.fromMillisecondsSinceEpoch(
            (json['date'] as Int64).toInt()),
        spouse1 = Person.deserialize(json['spouse1']),
        spouse2 = Person.deserialize(json['spouse2']);

  static Marriage deserialize(BsonBinary bsonBinary) =>
      _deserialize(bsonBinary, Marriage.fromJson);

  @override
  Map<String, dynamic> toJson() => {
        'date': date.millisecondsSinceEpoch,
        'spouse1': spouse1,
        'spouse2': spouse2,
      };
}

```

**Comment by adil192** [comment]
This wouldn't work with my `FriendGroup` example since a `List` is not `Serializable`.
There needs to be a recursive implementation which basically means this functionality has to be included in `BsonObject.bsonObjectFrom`.

> There are many serialization patterns, and several ways to do this kind of job.

I would say that `toJson` and `fromJson` are the most common ways to do this, especially in Dart, where the built-in JSON implementation uses these methods by default.

In the documentation for Dart's `json.encode(value, Function toEncodable)` function, we have:

> If toEncodable is omitted, it defaults to a function that returns the result of calling .toJson() on the unencodable object.

If you really want to retain the purity of your bson implementation, perhaps we can have pass a `toEncodable` function into the `BSON.serialize` function which is then passed to `BsonObject.bsonObjectFrom`. E.g.
```dart
// in bson package
factory BsonObject.bsonObjectFrom(var value, {Object? toEncodable(dynamic value)?}) {
    // ...
    } else if (value is Timestamp) {
      return BsonTimestamp(value);
    } else if (toEncodable != null) {
      return BsonObject.bsonObjectFrom(toEncodable(value));
    }
    throw Exception('Not implemented for $value');
  }
}
```

**Comment by giorgiofran** [comment]
Hi, with that approach you have to create a BsonObject for each class you want to serialize, isn't it?
Anyway, BSON is a standard that define how to serialize a certain range of basic types. If you want to use it, you have to pre-prepare your data so that it is compatible with the types managed.
The example I gave you goes in this direction, and I guess that you could easily update it to mange also lists.
Alternatively, you can clone this repository and do you own implementation.
I'm sorry, but I want to stay as close to the standard as possible.

**Comment by adil192** [comment]
> The example I gave you goes in this direction, and I guess that you could easily update it to mange also lists.

The example you gave isn't scalable. For example, my SBN note files are structured like this:
```json
{
  "pages" : [
    {
      "w" : 1000.0,
      "h" : 1400.0,
      "strokes" : [
        {
          "points" : [
            {
              "pressure" : 0.1,
              "x" : 0.0,
              "y" : 0.0
            }
          ]
        }
      ]
    }
  ]
}
```
Using a non-recursive solution would quickly get extremely verbose.

> I'm sorry, but I want to stay as close to the standard as possible.

That's completely fine of course. Would you be open to a small recursive helper function that allows a dev to use the following code:
```dart
final ComplexObject myComplexObject = ComplexObject();
/// Recursively calls toJson on all non-simple types until we have a simple data structure
final Map<String, dynamic> serialized = serializeJsonTypes(myComplexObject);
final BsonObject bson = BsonObject.bsonObjectFrom(serialized);
```

**Comment by giorgiofran** [comment]
We can talk about it. Next week I hope to have time to give a deeper look to this issue. Just a snall question, you need serialization to transfer data or to store it in MongoDb (In the first case it could be enough to transform the object into a binary format, in the second we have to create a document, otherwise in MongoDb you cannot read the contet)?

**Comment by adil192** [comment]
I'm using serialization to store the user's notes in files

**Comment by giorgiofran** [comment]
Hi, I have published version 5.0.0-2.0.dev of the BSON package.
It is still a dev version, so use it with caution.
In the example folder there is a case just to explain how to use it.
At the end I had to change the base classes ...
Please give it a try and let me know. Suggestions are welcome.

**Comment by adil192** [comment]
I've just looked through the v5.dev changes and this looks like it would take a lot of refactoring time to integrate into my app.
The goal of this PR was to minimise the difficulty of switching from JSON to BSON.

I think I'm going to stick to just using this fork since I don't really have time to refactor everything. Plus this is another breaking change in the app.

**Comment by giorgiofran** [comment]
I can repropose the toJson() methods, but the question is, why do you need them? And in which classes?
The idea is to have the Bson classes managed internally and to pass to the system only the Dart classes (including ObjectId, etc)

**Comment by giorgiofran** [comment]
As I was doing these changes I have also reorganized the sources. 
Which are the bigger problems that you are facing?

**Comment by giorgiofran** [comment]
For what I have understood from what you said, the refactoring that should done, but let me know if I'm wrong, is the following:
- Add the BsonSerializable mixin to the classes you want to serialize
- Override the toBson method (initially you could only call your existing toJson one)
- Register the class with a unique number and the method you use for recreating the instance (that could be your old fromJson() one).

That's all. 
Let me know if I was too much optimistic.

**Comment by adil192** [comment]
There's the things you've just mentioned, but on a very large number of classes, making it a tedious process.
And more importantly, this format is incompatible with the old format, so I'd need to handle migrating from ".sbn" and ".sbn2" to ".sbn3" file formats. The parsing code for all these formats gets messy very quickly.
Users would also not be able to access their notes on older versions, so this scenario is to be avoided as much as possible.

**Comment by giorgiofran** [comment]
The beta is out, I close this request.

**Pull request closed without merging**
