### PR TITLE
Fixed missing casts to decimal

### PR DESCRIPTION
**Pull request by ruicraveiro**
Hi,

Version 2.3.0 of the ```decimal``` package introduced a breaking change, which this PR adapts to.

Thanks!

Rui

### CODE REVIEW

**Comment by iamdineshkumar** [comment]
Why This PR not merged? This actually helps me to fix issue... Thanks...

**Comment by giorgiofran** [comment]
I'm sorry, I'm checking if using toDecimal() is enough, because the method can trhrow unexpectedly. I'm
 working on a solution, hope to have it available by the end of this week.

**Comment by iamdineshkumar** [comment]
> I'm sorry, I'm checking if using toDecimal() is enough, because the method can trhrow unexpectedly. I'm working on a solution, hope to have it available by the end of this week.

Noted... At the moment I am using this temp solution... Waiting for stable version

**Comment by ruicraveiro** [comment]
I submitted the PR then closed it because I used a temporary fork with the change applied and it worked on my prototypes, but broke other applications with more dependencies. Ideally, this should be fixed, upstream, by decimal's package maintainers by releasing a major version of the decimal package.

**Comment by ruicraveiro** [comment]
... which they won't: https://github.com/a14n/dart-decimal/issues/89

**Comment by giorgiofran** [comment]
Relase Bson 2.0.2 with the temporary fix suggested by Alexandre

**Pull request closed without merging**
